save_dir: workspace/cross_domain_eval_coco
model:
  weight_averager:
    name: ExpMovingAverager
    decay: 0.9998
  arch:
    name: NanoDetPlus
    detach_epoch: 10
    backbone:
      name: SFuseNet
      model_size: 1.0x
      out_stages: [2, 3, 4]
      activation: LeakyReLU
      pretrain: True
      groups: 4
      reduction_ratio: 8
    fpn:
      name: GhostPAN
      in_channels: [116, 232, 464]
      out_channels: 96
      kernel_size: 5
      num_extra_level: 1
      use_depthwise: True
      activation: LeakyReLU
    head:
      name: NanoDetPlusHead
      num_classes: 80 # COCO has 80 classes
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      kernel_size: 5
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0
    aux_head:
      name: SimpleConvHead
      num_classes: 80
      input_channel: 192
      feat_channels: 192
      stacked_convs: 4
      strides: [8, 16, 32, 64]
      activation: LeakyReLU
      reg_max: 7
data:
  val:
    name: CocoDataset
    img_path: D:/Projects/Mini-Projects/Mini-Project-1/coco2017/val2017
    ann_path: D:/Projects/Mini-Projects/Mini-Project-1/coco2017/annotations/instances_val2017.json
    input_size: [416, 416]
    keep_ratio: False
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]
  workers_per_gpu: 4
  batchsize_per_gpu: 16
  precision: 32
schedule:
  total_epochs: 1 # Evaluation only
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP
log:
  interval: 20
